name: CI

on:
  push:
    branches: [ main, dev, testing ]
  pull_request:
    branches: [ main, testing ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install linters
      run: |
        npm install -g htmlhint eslint stylelint stylelint-config-standard postcss postcss-scss

    # - name: Lint HTML
    #   run: htmlhint "**/*.html"

    - name: Lint JavaScript
      run: |
        echo 'export default [];' > eslint.config.mjs
        eslint "**/*.js"

    - name: Lint CSS
      run: |
        echo '{
          "extends": "stylelint-config-standard"
        }' > .stylelintrc.json
        stylelint "**/*.css"

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Validate PHP syntax
      run: |
        find . -name "*.php" -exec php -l {} \;
